ConstraintDef constraint_list[] = {
{ "element", CT_ELEMENT, 3, {{read_list, read_var, read_var, }}, },
{ "element_undefzero", CT_ELEMENT_UNDEFZERO, 3, {{read_list, read_var, read_var, }}, },
{ "element_one", CT_ELEMENT_ONE, 3, {{read_list, read_var, read_var, }}, },
{ "watchelement", CT_WATCHED_ELEMENT, 3, {{read_list, read_var, read_var, }}, },
{ "watchelement_one", CT_WATCHED_ELEMENT_ONE, 3, {{read_list, read_var, read_var, }}, },
{ "watchelement_undefzero", CT_WATCHED_ELEMENT_UNDEFZERO, 3, {{read_list, read_var, read_var, }}, },
{ "gacelement-deprecated", CT_GACELEMENT, 3, {{read_list, read_var, read_var, }}, },
{ "alldiff", CT_ALLDIFF, 1, {{read_list, }}, },
{ "gacalldiff", CT_GACALLDIFF, 1, {{read_list, }}, },
{ "gcc", CT_GCC, 3, {{read_list, read_constant_list, read_list, }}, },
{ "gccweak", CT_GCCWEAK, 3, {{read_list, read_constant_list, read_list, }}, },
{ "alldiffmatrix", CT_ALLDIFFMATRIX, 2, {{read_list, read_constant, }}, },
{ "watchneq", CT_WATCHED_NEQ, 2, {{read_var, read_var, }}, },
{ "diseq", CT_DISEQ, 2, {{read_var, read_var, }}, },
{ "__reify_diseq", CT_DISEQ_REIFY, 3, {{read_var, read_var, read_var, }}, },
{ "eq", CT_EQ, 2, {{read_var, read_var, }}, },
{ "__reify_eq", CT_EQ_REIFY, 3, {{read_var, read_var, read_var, }}, },
{ "minuseq", CT_MINUSEQ, 2, {{read_var, read_var, }}, },
{ "__reify_minuseq", CT_MINUSEQ_REIFY, 3, {{read_var, read_var, read_var, }}, },
{ "abs", CT_ABS, 2, {{read_var, read_var, }}, },
{ "ineq", CT_INEQ, 3, {{read_var, read_var, read_constant, }}, },
{ "watchless", CT_WATCHED_LESS, 2, {{read_var, read_var, }}, },
{ "lexleq[rv]", CT_GACLEXLEQ, 2, {{read_list, read_list, }}, },
{ "lexleq[quick]", CT_QUICK_LEXLEQ, 2, {{read_list, read_list, }}, },
{ "lexleq", CT_LEXLEQ, 2, {{read_list, read_list, }}, },
{ "lexless", CT_LEXLESS, 2, {{read_list, read_list, }}, },
{ "lexless[quick]", CT_QUICK_LEXLESS, 2, {{read_list, read_list, }}, },
{ "max", CT_MAX, 2, {{read_list, read_var, }}, },
{ "min", CT_MIN, 2, {{read_list, read_var, }}, },
{ "occurrence", CT_OCCURRENCE, 3, {{read_list, read_constant, read_var, }}, },
{ "occurrenceleq", CT_LEQ_OCCURRENCE, 3, {{read_list, read_constant, read_constant, }}, },
{ "occurrencegeq", CT_GEQ_OCCURRENCE, 3, {{read_list, read_constant, read_constant, }}, },
{ "product", CT_PRODUCT2, 2, {{read_2_vars, read_var, }}, },
{ "difference", CT_DIFFERENCE, 2, {{read_2_vars, read_var, }}, },
{ "weightedsumleq", CT_WEIGHTLEQSUM, 3, {{read_constant_list, read_list, read_var, }}, },
{ "weightedsumgeq", CT_WEIGHTGEQSUM, 3, {{read_constant_list, read_list, read_var, }}, },
{ "sumgeq", CT_GEQSUM, 2, {{read_list, read_var, }}, },
{ "sumleq", CT_LEQSUM, 2, {{read_list, read_var, }}, },
{ "watchsumgeq", CT_WATCHED_GEQSUM, 2, {{read_list, read_constant, }}, },
{ "watchsumleq", CT_WATCHED_LEQSUM, 2, {{read_list, read_constant, }}, },
{ "table", CT_WATCHED_TABLE, 2, {{read_list, read_tuples, }}, },
{ "negativetable", CT_WATCHED_NEGATIVE_TABLE, 2, {{read_list, read_tuples, }}, },
{ "watchvecneq", CT_WATCHED_VECNEQ, 2, {{read_list, read_list, }}, },
{ "staticvecneq", CT_STATIC_VECNEQ, 2, {{read_list, read_list, }}, },
{ "litsumgeq", CT_WATCHED_LITSUM, 3, {{read_list, read_constant_list, read_constant, }}, },
{ "pow", CT_POW, 2, {{read_2_vars, read_var, }}, },
{ "div", CT_DIV, 2, {{read_2_vars, read_var, }}, },
{ "div_undefzero", CT_DIV_UNDEFZERO, 2, {{read_2_vars, read_var, }}, },
{ "modulo", CT_MODULO, 2, {{read_2_vars, read_var, }}, },
{ "modulo_undefzero", CT_MODULO_UNDEFZERO, 2, {{read_2_vars, read_var, }}, },
{ "gadget", CT_GADGET, 1, {{read_list, }}, },
{ "disabled-or", CT_WATCHED_OR, 1, {{read_list, }}, },
{ "hamming", CT_WATCHED_HAMMING, 3, {{read_list, read_list, read_constant, }}, },
{ "not-hamming", CT_WATCHED_NOT_HAMMING, 3, {{read_list, read_list, read_constant, }}, },
{ "watched-or", CT_WATCHED_NEW_OR, 1, {{read_constraint_list, }}, },
{ "watched-and", CT_WATCHED_NEW_AND, 1, {{read_constraint_list, }}, },
{ "w-inset", CT_WATCHED_INSET, 2, {{read_var, read_constant_list, }}, },
{ "w-inintervalset", CT_WATCHED_ININTERVALSET, 2, {{read_var, read_constant_list, }}, },
{ "w-notinset", CT_WATCHED_NOT_INSET, 2, {{read_var, read_constant_list, }}, },
{ "w-inrange", CT_WATCHED_INRANGE, 2, {{read_var, read_constant_list, }}, },
{ "w-notinrange", CT_WATCHED_NOT_INRANGE, 2, {{read_var, read_constant_list, }}, },
{ "w-literal", CT_WATCHED_LIT, 2, {{read_var, read_constant, }}, },
{ "w-notliteral", CT_WATCHED_NOTLIT, 2, {{read_var, read_constant, }}, },
{ "reify", CT_REIFY, 2, {{read_constraint, read_var, }}, },
{ "reifyimply-quick", CT_REIFYIMPLY_QUICK, 2, {{read_constraint, read_var, }}, },
{ "reifyimply", CT_REIFYIMPLY, 2, {{read_constraint, read_var, }}, },
{ "true", CT_TRUE, 0, {{}}, },
{ "false", CT_FALSE, 0, {{}}, },
{ "check[gsa]", CT_CHECK_GSA, 1, {{read_constraint, }}, },
{ "check[assign]", CT_CHECK_ASSIGN, 1, {{read_constraint, }}, },
{ "forwardchecking", CT_FORWARD_CHECKING, 1, {{read_constraint, }}, },
{ "watchvecexists_less", CT_WATCHED_VEC_OR_LESS, 2, {{read_list, read_list, }}, },
{ "lighttable", CT_LIGHTTABLE, 2, {{read_list, read_tuples, }}, },
{ "haggisgac", CT_HAGGISGAC, 2, {{read_list, read_short_tuples, }}, },
{ "haggisgac-stable", CT_HAGGISGAC_STABLE, 2, {{read_list, read_short_tuples, }}, },
{ "str2plus", CT_STR, 2, {{read_list, read_tuples, }}, },
{ "shortstr2", CT_SHORTSTR, 2, {{read_list, read_short_tuples, }}, },
{ "gaceq", CT_GACEQ, 2, {{read_var, read_var, }}, },
{ "gacschema", CT_GACSCHEMA, 2, {{read_list, read_tuples, }}, },
{ "mddc", CT_MDDC, 2, {{read_list, read_tuples, }}, },
{ "negativemddc", CT_NEGATIVEMDDC, 2, {{read_list, read_tuples, }}, },
{ "test", CT_TEST, 1, {{read_list, }}, },
{ "vm", CT_VM, 3, {{read_list, read_tuples, read_tuples, }}, },
{ "vmsym", CT_VM_SYM, 3, {{read_list, read_tuples, read_tuples, }}, },
{ "tablevm", CT_TABLE_VM, 2, {{read_list, read_tuples, }}, },
{ "negativetablevm", CT_NEG_TABLE_VM, 2, {{read_list, read_tuples, }}, },
};